### ISSUE TITLE
XNote column disappeared

### ISSUE THREAD

**Issue by AndrewDillon** [xnotepp/xnote#123]
For each email address in Thunderbird 102.15.1, I had XNote column in Inbox, Drafts, Sent Items, All Mail, Bin but not Spam.

In most (but not all) of those folders, the XNote column's disappeared.

**Comment by opto** [comment]
That is by design of TB 115, they took that feature away. It is announced to come back sometime. Please try https://github.com/xnotepp/xnote/releases/tag/v4.2.0 as a workaround

**Comment by opto** [comment]
doublicate of #114

**Comment by AndrewDillon** [comment]
I said I had Thunderbird 102.15.1.
I didn't say there was no entry in column menu - there is. It isn't a duplicate of #114.

I said "the XNote column's disappeared". i.e. It needs reselecting for each email account & folder.

**Comment by opto** [comment]
column handling in TB is a bug in TB.
By design, one has to set the column showing in every single folder, or click the: set all folders like this.

If you had it showing and they disappeared, TB did something wrong with its column handling. I hope you are able to restore them. This is something I cannot do anything about.

Actually, the component responsible in TB is the "column picker"
