### ISSUE TITLE
Cannot set path and lost path information

### ISSUE THREAD

**Issue by cqix** [xnotepp/xnote#47]
After Update 3.1 Xnote lost the path information.
When I go to settings, the path is set to **[ProfD]XNote** and cannot be set. Neither by entering a path manually nor by clicking the systems select button.

Manually setting it, using **document.getElementById('storage.path').value = '/Users/myusername/mypath;** works.

After manually setting the path, i can use the systems select button again.
<img width="601" alt="Bildschirmfoto 2020-12-02 um 09 53 18" src="https://user-images.githubusercontent.com/219432/100850917-ca57a100-3484-11eb-9a72-80f3d81920e5.png">

**Comment by spumino810** [comment]
hello, could you explain better how to do it?

**Comment by cqix** [comment]
When I startet the app this morning, I realised, the messages where not there. 
I immediately checked the path, and it was as you can see in the screenshot.
I tried to uninstall/install the add-on, but it did not help. (Still **ProfD]XNote**)

Only manually setting the path via the developer console helped.
Restarting Thunderbird new keeps the paht information. 

Maybe it would be enough, to validate the path. At least one then can select it againg, if there was an error.

**Comment by spumino810** [comment]
I had the same problem this morning but I'm not good at development 😀, I solved it by installing the previous version ... I await an update ... thanks

**Comment by froilo** [comment]
While the fix is on its way, it should be possible to use the following workaround to this issue: Create an XNote for any message or create the directory "XNote" in your [Thunderbird profile directory](http://kb.mozillazine.org/Profile_folder_-_Thunderbird). After that the "Browse..." should work again in order to select a custom directory.

**Comment by froilo** [comment]
Version 3.1.1 already got approved. Could someone who had this issue please confirm that the issue is solved after upgrading to 3.1.1: https://addons.thunderbird.net/en-US/thunderbird/addon/xnotepp/versions/3.1.1

Note: If you have already been upgrade to 3.1.0, your earlier custom path will not be restored, but the button to select the path should be working again.

**Comment by cqix** [comment]
I can report, that 2 of my colleagues also lost the path information. 
Mac user with 3.1.1 could select the path straight away. So, yes the fix seem to help.
(FYO: Windows user with 3.1.0 looked like it nearly crashed but recoverd after some time and then showed the dialog.)
Thanks @froilo !

**Comment by areketsuku** [comment]
We're 5 people in office using same mail and sharing usefull information via xNote++ (shared folder on server for note path). I confirm that we're able to share notes again. Thanks for the fix.  (we're all runing windows 10).
