### ISSUE TITLE
Have full, unrestricted access to Thunderbird and your computer

### ISSUE THREAD

**Issue by fperal** [xnotepp/xnote#51]
When I browse to the addon inside thunderbird and click on permissions it says 
This add-on can 
* Access browser tabs
But when I click on "add to thunderbird"   it says

Add Xnote++?
It requires permission to
* Have full, unrestricted access to Thunderbird and your computer

Which sounds very scary.

**Comment by froilo** [comment]
I guess the reason why Thunderbird says that the add-on requires unrestricted access is that it has to use so called Web experiments to access Thunderbird internals that are not available through the Web extension API. There is no other way currently to get this done. The permissions on the add-ons page show what standard APIs are used. However, the source code is fully available here in GitHub so that you are free to review it in case of any doubts.
