### ISSUE TITLE
Feature Request: show note in message as QNote

### ISSUE THREAD

**Issue by damufo** [xnotepp/xnote#52]
Add the ability to put the note on the text of the message (as QNote - Thunderbird add-on).

![Captura de pantalla_2020-12-23_13-19-01](https://user-images.githubusercontent.com/4057369/102995505-7d199d00-4521-11eb-82e2-5518d233d6bd.png)

Very Thanks.

**Comment by opto** [comment]
in order to keep the message Display on screen for small screens (notebooks), I propose (and will prepare) the following:

allow to display ca. 3 lines of the note - take away the linefeeds. This is similar to what some forums do in their post listing: show post title and a few lines of the post.

In addition, have a button to show the full xnote

**Comment by opto** [comment]
done as described above. Will come in next version in a few days

**Comment by opto** [comment]
done
